### PR TITLE
WIP: Add testing for Fable.Import.Node

### PR DESCRIPTION
**Pull request by jgrund**
Currently, the node bindings do not have any tests to ensure correctness.

This makes it cumbersome to work with changes, as you need to manually test them.

Instead we can add tests that ensure the bindings are working as intended, and catch any regressions going forward.

This patch sets up a test directory (unsure if that's the best place to start something like this, or they should be nested in each bindings dir), and adds some tests for Node.Streams.

I have not added a travis / appveyor file, but we should be able to use the build pipeline feature of travis to have multiple parallel jobs .

I am also using Fable.Import.Jest for testing, but would be happy to switch to another runner if preferred.

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
This is a great idea! Yes, I need to be more disciplined with tests 😅 We can force test running before publishing a new version of the Node tests. Using the Jest bindings is perfect, in fact, I'd like to include it in Fable's default template :+1:

**Comment by jgrund** [comment]
@alfonsogarciacaro I've added a `.travis.yml` File that uses [build stages](https://docs.travis-ci.com/user/build-stages/).

With that, we can test any commits that come in.

I've also added a deploy step, so we can deploy specific packages just by tagging repo with the correct tag.

For instance, to deploy a new version of the node bindings once this lands, we just need to increment the version and tag the repo with a new version (for example `v0.4.0node`).

More of these deploy jobs can be added for each of the bindings, so publishing can be automated for all bindings.

**Comment by jgrund** [comment]
@alfonsogarciacaro Could you enable travis for this repo when you have a moment?

**Comment by alfonsogarciacaro** [comment]
Sure, there you go!

**Comment by alfonsogarciacaro** [comment]
How does the deployment work? Do I need to add my Nuget key to Travis or did you do it already?

**Comment by jgrund** [comment]
@alfonsogarciacaro You will need to add your nuget key under the same environment variable under travis settings (make sure it's hidden).

Then, you can cut a new release by bumping the version and tagging the commit where it matches the given regex, (ex: v0.4.0node). 

Once you tag, travis will pick it up and do a deployment.

**Comment by jgrund** [comment]
@alfonsogarciacaro Still more to do here, but this is consistently working.

Any issue to landing this as is and iterating further as we update bindings?

**Comment by alfonsogarciacaro** [comment]
Ah, no! We can absolutely merge it. I was just waiting for you to give the approval as it already has the WIP tag ;)

**Pull request merged**
