### PR TITLE
Improve Browser API

### PR DESCRIPTION
**Pull request by alfonsogarciacaro**
The Fable REPL has been updated and until loading libraries is enabled, people will likely use the browser API more often than normal Fable apps, so I'm trying to improve the bindings. I've used latest ts2fable and ported changes semi-automatically to the current file to have a better diff. The main changes are:

- **Replace `ResizeArray` with `IList`**: This allows users to pass either `ResizeArray` or a normal array to functions accepting `IList`. The main problem is numeric arrays as they're compiled as typed arrays by Fable. We can use `ResizeArray` only for numbers (there are not many cases in this file), go back to `ResizeArray` in all cases, or make sure typed arrays are converted to JS arrays when casting to `IList` (though [this is problematic in current version of Fable](https://github.com/fable-compiler/Fable/issues/1279#issuecomment-348730712)).
- **Use curried functions instead of `Func`**: this is already implemented in ts2fable.
- **Use `'Out` instead of `obj` as the output value for callbacks**: this is mainly so you can use `unit` as the return value in `addEventListener` callbacks instead of being forced to use `null`.
- **Add comments**: I used a script to port the comments from the ts2fable generated file to this one, they seem to have been placed in the right position, I hope there're no mismatches.

Maybe some of these changes can be applied also to the Node bindings or ts2fable. Could you please have a quick look and tell me what you think? @MangelMaxime @ctaggart @jgrund @whitetigle

### CODE REVIEW

**Comment by MangelMaxime** [comment]
About point 1, is `["a";"b"]`, `[|"a";"b"|]` valid type implementing `IList` ?

**Comment by jgrund** [comment]
Kind of an aside, but one thing I've noticed with the node bindings is the comments aren't appearing after using the published module.

**Comment by MangelMaxime** [comment]
To see the comments, I remember that in C# we needed to check a box "Generate XML output" or something like that perhaps this is related.

**Comment by alfonsogarciacaro** [comment]
@MangelMaxime F# list doesn't implement `IList` but array does (which is a bit weird as .NET arrays have fixed size). Only `[|1; 2|]` and `ResizeArray [|1; 2|]` would be compatible with `IList`. 

> A (rare) case of a custom type implementing `IList` could cause conflict but this would be problematic also because Fable replaces calls to `IList`, so we probably just need to forbid custom `IList` implementations.

About the documentation, you're right. I forgot to add the `GenerateDocumentationFile` property to .fsproj 😅 Fixed now.

**Comment by alfonsogarciacaro** [comment]
I've reverted the `ResizeArray` > `IList` change, it can probably make more harm than good at this point.

**Pull request merged**
