### PR TITLE
Added Service Worker definitions

### PR DESCRIPTION
**Pull request by whitetigle**
Hi!
I just added service worker definitions generated thanks to ts2fable from this file:

https://gist.githubusercontent.com/ithinkihaveacat/227bfe8aa81328c5d64ec48f4e4df8e5/raw/f69f0783e69f5827b20dbe3f3509ddbf73933768/service-worker.d.ts

I use them in my current project. It works on my side (at least the part I'm using)

### CODE REVIEW

**Comment by MangelMaxime** [comment]
Just for reference it's seems supported on all the modern browser: https://caniuse.com/#feat=serviceworkers

So I am ok to add it to Fable.Import.Browser

**Comment by whitetigle** [comment]
@alfonsogarciacaro maybe I should have used this [lib ](https://github.com/Microsoft/TypeScript/blob/a7c53c70d2d74520483a892eb3e9ca55daf655cf/lib/lib.dom.d.ts) instead?

**Comment by whitetigle** [comment]
Hi there, just so you know I've been working on [a sample featuring service workers](https://github.com/whitetigle/fable-pwa). It does not use the latest bindings (we need to review that first) but will once we're ok. 

My next goal: use fable to generate this [file](https://github.com/whitetigle/fable-pwa/blob/master/docs/service-worker.js).

Would that work? Would that be interesting?

**Comment by whitetigle** [comment]
Thanks!

**Comment by Nhowka** [comment]
I was fiddling with the bindings and I managed to create a working service worker with F# only, but it's missing the `addEventListener_xxx` to make it better to use as `Event` is not enough for the most common use-cases...

**Comment by alfonsogarciacaro** [comment]
Thanks @Nhowka! Could you please send a PR to add them [as in here](https://github.com/whitetigle/fable-import/blob/6deae2a2d596d2adb81fa86dd94395dba8dd9867/Browser/Fable.Import.Browser.fs#L293-L300)?

**Comment by Nhowka** [comment]
Added in #66

**Comment by whitetigle** [comment]
Bravo @Nhowka! 👏 
Thanks for your work on this. I'll update my PWA projects to remove all js code now. F# all the way 😉

**Pull request merged**
