### PR TITLE
TreeItem.command and window.registerTreeDataProvider

### PR DESCRIPTION
**Pull request by fsoikin**

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
Thanks!

**Comment by fsoikin** [comment]
Can you please publish a new version? I need it for Ionide.

**Comment by alfonsogarciacaro** [comment]
I'll do! Do you want me make you co-owner of the Fable.Import.VSCode package? If so, what's your nuget alias?

**Comment by fsoikin** [comment]
I would be honored to! My NuGet alias is "fsoikin".

While we're on the subject, what do you think about semi-automated publishing?
On some of my projects, I have the build script set to publish when (1) building from CI (Travis), and (2) the current branch is "publish", and (3) the build hasn't been triggered from a pull request.
When I want to publish, I would just move the "publish" branch to latest master. I can be sure that the published version is built and tested, and the next version gets assigned automatically by the CI server.

**Comment by forki** [comment]
Publishing from CI is often ok, but I personally prefer to do it from local. That gives me a bit more control and I can react much faster if something goes wrong. At least for fake and paket this is super important for me. 

That said in our company we publish a lot from CI. Mostly because it does not ship instantly to users.

**Comment by alfonsogarciacaro** [comment]
Thanks @fsoikin! Automating the publishing is a nice idea. I'm still trying to improve my automation skills :wink: Though the main difficulty to publish from a monorepo like this is one, is updating values during the CI server build. For example, the build script right now compares the version in the RELEASE_NOTES with the version in the .fsproj file, if they're different it publishes the package and then updates the version in the .fsproj file. I'm not sure how would that work in the CI server, as my understanding is CI server builds shouldn't modify the repo (not sure if they can do commits on their own).

BTW @Krzysztof-Cieslak, do you have an Nuget alias to also make you coowner of the package?

**Pull request merged**
